<?php include 'inc/functions.php'; ?>
<?php include 'inc/header.phtml'; ?>
    <a class="btn btn-sm btn-outline-danger pull-right" href="/">Reset</a>
    <select class="form-control form-control-inline form-control-sm pull-right" name="search_by" id="search_by">
<?php foreach ($searchFields as $searchField): ?>
<?php if ($searchField != 'id'): ?>
        <option value="<?=$searchField; ?>"<?=($searchedBy == $searchField) ? ' selected="selected"' : null; ?>><?=convertCase($searchField); ?></option>
<?php endif; ?>
<?php endforeach; ?>
    </select>
    <input class="form-control form-control-inline form-control-sm pull-right" id="search_for" name="search_for" type="text" value="<?=$searched; ?>" placeholder="Search..." size="20" />
    <h1><?=$title;?> (<span id="result-count"><?=$resultCount; ?></span>)</h1>
    <table id="results" class="table table-bordered" cellpadding="0" cellspacing="0"
           data-url="/users"
           data-url-count="/users/count"
           data-page="<?=(int)$page; ?>"
           data-limit="<?=(int)$limit; ?>"
           data-sort="<?=$sort; ?>"
           data-filter="<?=$filter; ?>">
        <thead>
            <tr>
                <th>#</th>
<?php foreach ($searchFields as $searchField): ?>
                <th><a href="/?limit=<?=$limit; ?>&sort=<?=getSort($searchField) . getQuery(['sort', 'limit']); ?>"><?=convertCase($searchField); ?></a></th>
<?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
<?php if (count($results) == 0): ?>
            <tr>
                <td colspan="<?=(count($searchFields) + 1); ?>"><p class="no-results">There are currently no results.</p></td>
            </tr>
<?php else: ?>
<?php foreach ($results as $i => $result): ?>
            <tr>
                <td><?=($i + 1); ?></td>
<?php foreach ($searchFields as $searchField): ?>
                <td><?=$result[$searchField]; ?></td>
<?php endforeach; ?>
            </tr>
<?php endforeach; ?>
<?php endif; ?>
        </tbody>
    </table>
    <div id="loading"></div>
<?php include 'inc/footer.phtml'; ?>