<?php include 'inc/functions.php'; ?>
<?php include 'inc/header.phtml'; ?>
    <a class="btn btn-sm btn-outline-primary pull-right" href="/">Reset</a>
    <select class="form-control form-control-inline form-control-sm pull-right" name="search_by" id="search_by">
<?php foreach ($searchFields as $searchField): ?>
<?php if ($searchField != 'id'): ?>
        <option value="<?=$searchField; ?>"<?=($searchedBy == $searchField) ? ' selected="selected"' : null; ?>><?=convertCase($searchField); ?></option>
<?php endif; ?>
<?php endforeach; ?>
    </select>
    <input class="form-control form-control-inline form-control-sm pull-right" id="search_for" name="search_for" type="text" value="<?=$searched; ?>" placeholder="Search..." size="20" />
    <h1><?=$title;?> (<span id="result-count"><?=$resultCount; ?></span>)</h1>
<?php
$exportQuery = getQuery(['sort', 'limit'], false);
if (!empty($sort)):
    $exportQuery = '?sort=' . $sort . ((!empty($exportQuery)) ? '&' . $exportQuery : null);
elseif (!empty($exportQuery)):
    $exportQuery = '?' . $exportQuery;
endif;
?>
    <form id="filter-form" action="/" method="get">
        <select class="form-control form-control-inline form-control-sm " name="fields[]" id="fields" multiple="multiple" size="2">
<?php foreach ($allSearchFields as $searchField): ?>
            <option value="<?=$searchField;?>"<?=(in_array($searchField, $fields)) ? ' selected="selected"' : ''; ?>><?=convertCase($searchField); ?></option>
<?php endforeach; ?>
        </select>
        <button class="btn btn-sm btn-outline-primary filter-btn">Filter</button>
<?php if (!empty($filter)): ?>
        <input type="hidden" id="filter" name="filter[]" value="<?=$filter; ?>" />
<?php endif; ?>
    </form>
    <a href="/export<?=$exportQuery; ?>" id="export-btn" class="btn btn-sm btn-outline-primary filter-btn">Export</a>
    <a href="/" class="btn btn-sm btn-outline-primary filter-btn">Reset</a>
    <table id="results" class="table table-bordered table-striped" cellpadding="0" cellspacing="0"
           data-url="/users"
           data-url-export="/export"
           data-page="<?=(int)$page; ?>"
           data-limit="<?=(int)$limit; ?>"
           data-sort="<?=$sort; ?>"
           data-filter="<?=$filter; ?>"
           data-fields="<?=implode(',', $fields); ?>"
           data-numbered="<?=$numbered; ?>"
           data-no-results="<?=$noResults; ?>">
        <thead>
            <tr>
<?php if ($numbered): ?>
                <th>#</th>
<?php endif; ?>
<?php foreach ($searchFields as $searchField): ?>
                <th><a href="/?limit=<?=$limit; ?>&sort=<?=getSort($searchField) . getQuery(['sort', 'limit']); ?>"><?=convertCase($searchField); ?></a></th>
<?php endforeach; ?>
            </tr>
        </thead>
        <tbody>
<?php if (count($results) == 0): ?>
            <tr>
                <td colspan="<?=(count($searchFields) + (int)($numbered)); ?>"><p class="no-results"><?=$noResults; ?></p></td>
            </tr>
<?php else: ?>
<?php foreach ($results as $i => $result): ?>
            <tr>
<?php if ($numbered): ?>
                <td><?=($i + 1); ?></td>
<?php endif; ?>
<?php foreach ($searchFields as $searchField): ?>
                <td><?=$result[$searchField]; ?></td>
<?php endforeach; ?>
            </tr>
<?php endforeach; ?>
<?php endif; ?>
        </tbody>
    </table>
    <div id="loading"></div>
<?php include 'inc/footer.phtml'; ?>